imports:
    - { resource: parameters.yml }
    - { resource: "@SplashWidgetsBundle/Resources/config/blocks.yml" }
    - { resource: "@SplashWidgetsBundle/Resources/config/demo.yml" }
    - { resource: "@SplashWidgetsBundle/Resources/config/test.yml" }
    
    
# Framework Configuration
framework:
    translator:      { fallbacks: ["%locale%"] }
    router:
        resource:   "%kernel.root_dir%/routing_test.yml"
    templating:
        engines: ['twig']  
    form:           ~
    test: ~
    session:
        storage_id: session.storage.filesystem
    
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        
# Mopa Bootstrap
mopa_bootstrap:
    menu: ~
    form: ~
    
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: true

    